# -*- coding: utf-8 -*-
#
# Li-Pro.Net Sphinx Primer documentation build configuration file,
# created by sphinx-quickstart on Sat Sep  5 12:37:04 2020.
#
# The configuration directory must contain a file named conf.py.
# This file (containing Python code) is execfile()d with the
# current directory set to its containing dir and is called the
# "build configuration file" and contains (almost) all configuration
# needed to customize Sphinx input and output behavior.
#
# This file only contains a selection of the most common options.
# For a full list see the documentation:
#
# http://www.sphinx-doc.org/en/3.x/config
#
# An optional file docutils.conf can be added to the configuration
# directory to adjust Docutils configuration if not otherwise overridden
# or set by Sphinx.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.


# -- Path setup --------------------------------------------------------------

import sphinx_rtd_theme
import sphinx
import semver
import git
import sys
import os

logcfg = sphinx.util.logging.getLogger(__name__)
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

if "DOCSRC" not in os.environ:
    DOCSRC = os.path.abspath(os.getcwd())
else:
    DOCSRC = os.path.abspath(os.environ["DOCSRC"])

if "DOCTOP" not in os.environ:
    DOCTOP = os.path.abspath(os.path.join(DOCSRC, '..'))
else:
    DOCTOP = os.path.abspath(os.environ["DOCTOP"])

if "DOCBLD" not in os.environ:
    DOCBLD = os.path.abspath(os.path.join(DOCTOP, 'build'))
else:
    DOCBLD = os.path.abspath(os.environ["DOCBLD"])

# Add the 'extensions' directory to sys.path, to enable finding Sphinx
# extensions within. If extensions (or modules to document with autodoc)
# are in another directory, add these directories to sys.path here. If the
# directory is relative to the documentation root, use os.path.abspath to
# make it absolute, like shown here.
sys.path.insert(0, os.path.join(DOCSRC, '_extensions'))


# -- Project information -----------------------------------------------------

project = 'Li-Pro.Net Sphinx Primer'
title = project
author = 'The LP/N Documentation Team'
publisher = 'Li–Pro.Net'
contactaddr = 'Jena, Germany'
contactemail = 'info@li-pro.net'
copyright = '2020, ' + publisher + ', ' + author + ' and individual contributors.'
category = 'Miscellaneous'
about = 'How to write Li-Pro.Net documentation with Sphinx.'
keywords = 'Sphinx, Docutils, reStructuredText, howto, primer'

if on_rtd:
    git_describe = ('--dirty=+RTDEXT', '--broken=+broken')
else:
    git_describe = ('--dirty=+dirty', '--broken=+broken')

try:
    repo = git.Repo(search_parent_directories=True)
    semv = semver.VersionInfo.parse(repo.git.describe(git_describe))
except:
    # fallback to unknown version / release
    semv = semver.VersionInfo.parse('0.0.0-invalid+unknown')

# The short X.Y.Z version
version = str(semv.finalize_version())

# The full version, including alpha/beta/rc tags
release = str(semv)

# Single target file names
namespace = 'net.li-pro.doc.sphinx-primer.' + version + '.'
basename = 'lpn-doc-sphinx-primer'

logcfg.info(project + ' ' + release, color='yellow')


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-needs_sphinx
#
needs_sphinx = '3.2.1'
build_sphinx = sphinx.__version__

# This value can be a dictionary specifying version requirements for
# extensions in 'extensions'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-needs_extensions
#
needs_extensions = {
#   'sphinx.ext.autodoc':                       needs_sphinx,
#   'sphinx.ext.autosummary':                   needs_sphinx,
    'sphinx.ext.autosectionlabel':              needs_sphinx,
    'sphinx.ext.doctest':                       needs_sphinx,
    'sphinx.ext.coverage':                      needs_sphinx,
    'sphinx.ext.todo':                          needs_sphinx,
    'sphinx.ext.ifconfig':                      needs_sphinx,
    'sphinx.ext.intersphinx':                   needs_sphinx,
    'sphinx.ext.extlinks':                      needs_sphinx,
#   'sphinx.ext.viewcode':                      needs_sphinx,
#   'sphinx.ext.linkcode':                      needs_sphinx,
#   'sphinx.ext.imgmath':                       needs_sphinx,
    'sphinx.ext.mathjax':                       needs_sphinx,
#   'sphinx.ext.jsmath':                        needs_sphinx,
#   'sphinx.ext.graphviz':                      needs_sphinx,
#   'sphinx.ext.imgconverter':                  needs_sphinx,
#   'sphinx.ext.inheritance_diagram':           needs_sphinx,
#   'sphinx_rtd_theme':                         '0.5.0',
#   'sphinxcontrib.inkscapeconverter':          '1.1.0',
    'sphinxcontrib.rsvgconverter':              '1.1.0',
#   'sphinxcontrib.cairosvgconverter':          '1.1.0',
#   'sphinxcontrib.email':                      '0.3.3',
#   'sphinxcontrib.bibtex':                     '1.0.0',
    'sphinxcontrib.blockdiag':                  '2.0.0',
    'sphinxcontrib.seqdiag':                    '2.0.0',
    'sphinxcontrib.actdiag':                    '2.0.0',
    'sphinxcontrib.nwdiag':                     '2.0.0',
    'sphinxcontrib.rackdiag':                   '2.0.0',
    'sphinxcontrib.packetdiag':                 '2.0.0',
#   'sphinxcontrib.inlinesyntaxhighlight':      '0.2',
#   'sphinxcontrib.programscreenshot':          '0.0.5',
#   'sphinxcontrib.programoutput':              '0.16',
#   'sphinxcontrib.spelling':                   '5.4.0',
    'sphinxcontrib.tikz':                       '0.4.9',
#   'sphinx_tabs.tabs':                         '1.3.0',
#   'sphinx_panels':                            '0.5.1',
#   'linuxdoc.rstFlatTable':                    '20200812',
#   'matplotlib.sphinxext.mathmpl':             '3.3.2',
#   'matplotlib.sphinxext.plot_directive':      '3.3.2',
}

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-extensions
#
extensions = [
#   'sphinx.ext.autodoc',
#   'sphinx.ext.autosummary',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.doctest',
    'sphinx.ext.coverage',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx.ext.intersphinx',
    'sphinx.ext.extlinks',
#   'sphinx.ext.viewcode',
#   'sphinx.ext.linkcode',
#   'sphinx.ext.imgmath',
    'sphinx.ext.mathjax',
#   'sphinx.ext.jsmath',
#   'sphinx.ext.graphviz',
#   'sphinx.ext.imgconverter',
#   'sphinx.ext.inheritance_diagram',
    'sphinx_rtd_theme',
#   'sphinxcontrib.inkscapeconverter',
    'sphinxcontrib.rsvgconverter',
#   'sphinxcontrib.cairosvgconverter',
    'sphinxcontrib.email',
    'sphinxcontrib.bibtex',
    'sphinxcontrib.blockdiag',
    'sphinxcontrib.seqdiag',
    'sphinxcontrib.actdiag',
    'sphinxcontrib.nwdiag',
    'sphinxcontrib.rackdiag',
    'sphinxcontrib.packetdiag',
    # w/o maintenance since 2013: 'sphinxcontrib.inlinesyntaxhighlight',
    # w/o maintenance since 2012: 'sphinxcontrib.programscreenshot',
    'sphinxcontrib.programoutput',
    'sphinxcontrib.spelling',
    'sphinxcontrib.tikz',
    'sphinx_tabs.tabs',
    # not yet, see below "Specific configuration": 'sphinx_panels',
    'linuxdoc.rstFlatTable',
    'matplotlib.sphinxext.mathmpl',
    'matplotlib.sphinxext.plot_directive',
    'ldsp.ultimate_replacements',
    'ldsp',
]


# -- Specific configuration --------------------------------------------------


path_extra = os.path.join(DOCSRC, '_extra')
logcfg.info('EXTRAS     path is: "{}"'.format(path_extra), color='green')

path_images = os.path.join(DOCSRC, '_images')
logcfg.info('IMAGES     path is: "{}"'.format(path_images), color='green')

path_templates = os.path.join(DOCSRC, '_templates')
logcfg.info('TEMPLATE   path is: "{}"'.format(path_templates), color='green')

path_static = os.path.join(DOCSRC, '_static')
logcfg.info('STATIC     path is: "{}"'.format(path_static), color='green')

path_dejavu = os.path.join(path_static, 'fonts', 'DejaVu')
logcfg.info('DejaVu     path is: "{}"'.format(path_dejavu), color='green')

path_wenquanyi = os.path.join(path_static, 'fonts', 'WenQuanYi')
logcfg.info('WenQuanYi  path is: "{}"'.format(path_wenquanyi), color='green')

if tags.has('release'):  # pylint: disable=undefined-variable
    is_release = True
    docs_title = 'Docs / %s' %(version)
else:
    is_release = False
    docs_title = 'Docs / Latest'

# Use the Sphinx panel extension only when it is really applicable, quite new.
# There are some cross side effects with the Sphinx tabs extension.
# tags.add("sphinx_panels")  # pylint: disable=undefined-variable
# tags.add("sphinx_panels_no_boostrap_css")  # pylint: disable=undefined-variable
if tags.has("sphinx_panels"):  # pylint: disable=undefined-variable
    extensions.append('sphinx_panels')
    if tags.has("sphinx_panels_no_boostrap_css"):  # pylint: disable=undefined-variable
        panels_add_boostrap_css = False  # default is: True
else:
    # use the locally mocked extension instead
    extensions.append('ldsp.mock_sphinx_panels')


# -- Sphinx Basic Configuration ----------------------------------------------

# Add any paths that contain templates here, relative to this directory.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-templates_path
#
templates_path = ['{}'.format(path_templates)]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-internationalization
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-language
#
language = 'en'

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-source_suffix
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-source_encoding
#
#source_encoding = 'utf-8-sig'

# If given, a dictionary of parser classes for different source suffices.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-source_parsers
#
#source_parsers = {'.md': 'recommonmark.parser.CommonMarkParser'}

# The master toctree document.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-master_doc
#
master_doc = 'index'

# There are two options for replacing |today|.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-today
#
# Either, you set today to some non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-exclude_patterns
#
exclude_patterns = []

# A string of reStructuredText that will be included at the beginning of every
# source file that is read.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-rst_prolog
#
rst_prolog = '''
.. include:: /{docsrc}/docroles.rsti
.. include:: /{docsrc}/docmeta.rsti
.. |CREDITS| replace:: :download:`CREDITS </{docsrc}/CREDITS>`
.. |LICENSE| replace:: :download:`LICENSE </{docsrc}/LICENSE>`
.. |publisher| replace:: {publisher}
.. |copyright| replace:: {copyright}
.. |project| replace:: {project}
.. |title| replace:: {title}
.. |author| replace:: {author}
.. |about| replace:: {about}
.. |contactaddr| replace:: {contactaddr}
.. |contactemail| replace:: {contactemail}
.. meta::
   :subject: {project}
   :description: {about}
   :keywords: {keywords}
   :author: {author}
   :publisher: {publisher}
   :copyright: {copyright}
'''.format(
    docsrc = DOCSRC,
    publisher = publisher,
    copyright = copyright,
    project = project,
    title = title,
    author = author,
    about = about,
    keywords = keywords,
    contactaddr = contactaddr,
    contactemail = contactemail,
)

# A string of reStructuredText that will be included at the end of every source
# file that is read. This is the right place to add substitutions that should be
# available in every file.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-rst_epilog
#
rst_epilog = '''
.. include:: /{docsrc}/termsgloss.rsti
.. include:: /{docsrc}/docextlnk.rsti
.. include:: /{docsrc}/docunicode.rsti
'''.format(
    docsrc = DOCSRC
)

# This change will allow us to use bare back-tick notation to let
# Sphinx hunt for a reference, starting with normal "document"
# references such as :ref:, but also including :c: and :cpp: domains
# (potentially) helping with API (doxygen) references simply by using
# `name`
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-primary_domain
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-default_role
#
#primary_domain = 'cpp'
default_role = 'any'

# If true, '()' will be appended to :func: etc. cross-reference text.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-add_function_parentheses
#
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-add_module_names
#
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-show_authors
#
#show_authors = False
show_authors = True

# The name of the Pygments (syntax highlighting) style to use.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-pygments_style
#
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-modindex_common_prefix
#
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-keep_warnings
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-suppress_warnings
#
#keep_warnings = False
suppress_warnings = [
    'epub.unknown_project_files',  ## reduce size of epub_exclude_files
]

# If true, figures, tables and code-blocks are automatically numbered if they
# have a caption. At same time, the numref role is enabled. For now, it works
# only with the HTML builder and LaTeX builder. Default is False.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig
#
numfig = True

# A dictionary mapping 'figure', 'table' and 'code-block' to strings that are
# used for format of figure numbers. Default is to use 'Fig. %s' for 'figure',
# 'Table %s' for 'table' and 'Listing %s' for 'code-block'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig_format
#
numfig_format = {
    'code-block': 'Listing %s',
    'sections': 'Section %s',
    'figure': 'Figure %s',
    'table': 'Table %s',
}

# The scope of figure numbers, that is, the numfig feature numbers figures in
# which scope. 0 means “whole document”. 1 means “in a section”. Sphinx numbers
# like x.1, x.2, x.3... 2 means “in a subsection”. Sphinx numbers like x.x.1,
# x.x.2, x.x.3..., and so on. Default is 1.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig_secnum_depth
#
numfig_secnum_depth = 1

# Set this option to True if you want all displayed math to be numbered.
# The default is False.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-math_number_all
#
math_number_all = True

# A string used for formatting the labels of references to equations. The
# {number} place-holder stands for the equation number. Example: 'Eq.{number}'
# gets rendered as, for example, Eq.10.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-math_eqref_format
#
math_eqref_format = 'Equastion {number}'

# If True, displayed math equations are numbered across pages when numfig is
# enabled. The numfig_secnum_depth setting is respected. The eq, not numref,
# role must be used to reference equation numbers. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-math_numfig
#
# math_numfig = False

# A URL to cross-reference manpage directives.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-manpages_url
#
manpages_url = 'https://manpages.debian.org/{path}'

# A User-Agent of Sphinx. It is used for a header on HTTP access
# (ex. linkcheck, intersphinx and so on).
# Default is "Sphinx/X.Y.Z requests/X.Y.Z python/X.Y.Z".
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-user_agent
#
#user_agent = 'Sphinx/X.Y.Z requests/X.Y.Z python/X.Y.Z

# If true, Sphinx verifies server certifications. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-tls_verify
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-tls_cacerts
#
# tls_verify = True
# tls_verify = False

# some configuration for linkcheck builder
#   noticed that we're getting false-positive link errors on different server,
#   I suspect because it's taking too long for the server to respond so bump
#   up the timeout (default=5) and turn off anchor checks (so only a HEAD
#   request is done - much faster). Leave the ignore commented in case we want
#   to remove different server link checks later...

#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_ignore
#
#linkcheck_ignore = ['http://localhost:\d+/']
linkcheck_ignore = [
#   'http://mirrors.ctan.org/',    # Causes SSL Server Error: CERTIFICATE_VERIFY_FAILED
#   'http://www.idpf.org/',        # Causes 500 Server Error: internal server error
#   'https://docs.bareos.org/',    # Causes 503 Server Error: service unavailable
    'https://www.amazon.com/dp/',  # Causes 503 Server Error: service unavailable
    'http://localhost:\d+/',
]

# The number of times the linkcheck builder will attempt to check a URL before
# declaring it broken. Defaults to 1 attempt.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_retries
#
# linkcheck_retries = 1
linkcheck_retries = 5

# A timeout value, in seconds, for the linkcheck builder. The default is to use
# Python’s global socket timeout.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_timeout
#
linkcheck_timeout = 60

# The number of worker threads to use when checking links.
# Default is 5 threads.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_workers
#
# linkcheck_workers = 5
linkcheck_workers = 10

# True or false, whether to check the validity of #anchors in links.
# Since this requires downloading the whole document, it’s considerably
# slower when enabled. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_anchors
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_anchors_ignore
#
#linkcheck_anchors = True
linkcheck_anchors = False


# -- Extension configuration -------------------------------------------------


# -- Options for sphinx.ext.autodoc -- Include documentation from docstrings -
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/autodoc.html
#


# -- Options for sphinx.ext.autosummary -- Generate autodoc summaries --------
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/autosummary.html
#


# -- Options for sphinx.ext.autosectionlabel -- Allow reference sections -----
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/autosectionlabel.html
#

# Internally, this extension generates the labels for each section. If same
# section names are used in whole of document, any one is used for a target
# by default. The autosectionlabel_prefix_document configuration variable
# can be used to make headings which appear multiple times but in different
# documents unique.

# True to prefix each section label with the name of the document it is in,
# followed by a colon. For example, index:Introduction for a section called
# Introduction that appears in document index.rst. Useful for avoiding
# ambiguity when the same section heading appears in different documents.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/autosectionlabel.html#confval-autosectionlabel_prefix_document
#
autosectionlabel_prefix_document = True


# -- Options for sphinx.ext.doctest -- Test snippets in the ------------------
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/doctest.html
#


# -- Options for sphinx.ext.coverage -- Collect doc coverage stats -----------
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/coverage.html
#


# -- Options for sphinx.ext.todo -- Support for todo items -------------------
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/todo.html
#

# If this is True, `todo` and `todoList` produce output, else they produce
# nothing. The default is False.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/todo.html#confval-todo_include_todos
#
todo_include_todos = True


# -- Options for sphinx.ext.ifconfig -- Include content based on configuration
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/ifconfig.html
#


# -- Options for sphinx.ext.intersphinx -- Link to other projects ------------
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/intersphinx.html
#

# This extension can generate automatic links to the documentation
# of objects in other projects. Usage is simple: whenever Sphinx
# encounters a cross-reference that has no matching target in the
# current documentation set, it looks for targets in the documentation
# sets configured in intersphinx_mapping.

# This config value contains the locations and names of other projects
# that should be linked to in this documentation.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/intersphinx.html#confval-intersphinx_mapping
#
# Example configuration for intersphinx: refer to the Python standard library.
# intersphinx_mapping = {'https://docs.python.org/3/': None}

# if on_rtd:
#     intersphinx_mapping = {
#         'sphinx': ('/Users/rexut/checkouts/sphinx/doc/_build/html/', None),
#     }
# else:
intersphinx_mapping = {
    #
    # Standard reference to this docs, with local objects.inv
    #

    # python -m sphinx.ext.intersphinx 'docs/_build/html/objects.inv'
    # '': ('{}/html/'.format(DOCBLD), None),

    #
    # Standard reference to web docs, with web objects.inv
    #

    # python -m sphinx.ext.intersphinx 'https://docs.python.org/3/objects.inv'
    'pydocs': ('https://docs.python.org/3/', None),

    # python -m sphinx.ext.intersphinx 'https://devguide.python.org/objects.inv'
    'pydevguide': ('https://devguide.python.org/', None),

    # python -m sphinx.ext.intersphinx 'https://www.sphinx-doc.org/en/3.x/objects.inv'
    'sphinx': ('https://www.sphinx-doc.org/en/3.x/', None),

    # python -m sphinx.ext.intersphinx 'https://rest-sphinx-memo.readthedocs.io/en/stable/objects.inv'
    'spxmemo': ('https://rest-sphinx-memo.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinxcontrib-spelling.readthedocs.io/en/stable/objects.inv'
    'scspelling': ('https://sphinxcontrib-spelling.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinxcontrib-bibtex.readthedocs.io/en/stable/objects.inv'
    'scbibtex': ('https://sphinxcontrib-bibtex.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://return42.github.io/linuxdoc/objects.inv'
    'lxdoc': ('https://return42.github.io/linuxdoc/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinxcontrib-programoutput.readthedocs.io/en/stable/objects.inv'
    'scprgout': ('https://sphinxcontrib-programoutput.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://matplotlib.org/objects.inv'|less
    'mplref': ('https://matplotlib.org/', None),

    # python -m sphinx.ext.intersphinx 'https://matplotlib.org/sampledoc/objects.inv'|less
    'mplsam': ('https://matplotlib.org/sampledoc/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinxcontrib-tikz.readthedocs.io/en/latest/objects.inv'
    'sctikz': ('https://sphinxcontrib-tikz.readthedocs.io/en/latest/', None),

    # python -m sphinx.ext.intersphinx 'http://blockdiag.com/en/objects.inv'|less
    'bldiag': ('http://blockdiag.com/en/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinx-tabs.readthedocs.io/en/stable/objects.inv'
    'spxtabs': ('https://sphinx-tabs.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinx-panels.readthedocs.io/en/stable/objects.inv'
    'spxpanels': ('https://sphinx-panels.readthedocs.io/en/stable/', None),

    #
    # Drawing the Docutils objects.inv from a RTD server,
    # but referring to the 0.16 web docs
    # Idea comes from https://sphobjinv.readthedocs.io/en/latest/
    #

    # python -m sphinx.ext.intersphinx 'https://docutils.readthedocs.io/en/sphinx-docs/objects.inv'
#   'docutils': ('https://docutils.sourceforge.io/docs/',
#                'https://docutils.readthedocs.io/en/sphinx-docs/objects.inv'),
}


# -- Options for sphinx.ext.extlinks -- Markup to shorten external links -----
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/extlinks.html
#

# This extension is meant to help with the common pattern of having many
# external links that point to URLs on one and the same site, e.g. links
# to bug trackers, version control web interfaces, or simply subpages in
# other websites. It does so by providing aliases to base URLs, so that
# you only need to give the subpage name when creating a link.

# This config value must be a dictionary of external sites, mapping unique
# short alias names to a base URL and a prefix.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/extlinks.html#confval-extlinks
#
extlinks = {
    'wikide':       ('https://de.wikipedia.org/wiki/%s', 'German Wikipedia: '),
    'wikien':       ('https://en.wikipedia.org/wiki/%s', 'English Wikipedia: '),
    'wikimedia':    ('https://upload.wikimedia.org/wikipedia/commons/%s', 'Wikimedia: '),
    'superuser':    ('https://superuser.com/%s', 'Superuser: '),
    'steamcoded':   ('https://steamcoded.org/lessons/%s', 'STEAMcoded.org: '),
    'dufaq':        ('https://docutils.sourceforge.io/FAQ.html#%s', ''),
    'dutodo':       ('https://docutils.sourceforge.io/docs/dev/todo.html#%s', ''),
    'duuser':       ('https://docutils.sourceforge.io/docs/user/rst/%s.html', ''),
    'durole':       ('https://docutils.sourceforge.io/docs/ref/rst/roles.html#%s', ''),
    'dudir':        ('https://docutils.sourceforge.io/docs/ref/rst/directives.html#%s', ''),
    'duref':        ('https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#%s', ''),
    'spxpanels':    ('https://sphinx-panels.readthedocs.io/en/stable/index.html#%s', ''),
}


# -- Options for sphinx.ext.viewcode -- Add links to highlighted source code -
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/viewcode.html
#


# -- Options for sphinx.ext.linkcode -- Add external links to source code ----
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/linkcode.html
#


# -- Options for sphinx.ext.*math* -- Math support for HTML outputs in Sphinx
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/math.html
#
#    sphinx.ext.imgmath -- Render math as images
#    sphinx.ext.mathjax -- Render math via JavaScript (prefered)
#    sphinx.ext.jsmath  -- Render math via JavaScript
#


# -- Options for sphinx.ext.graphviz -- Add Graphviz graphs ------------------
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/graphviz.html
#


# -- Options for sphinx.ext.imgconverter -- Converter using Imagemagick ------
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/inheritance.html
#
# Note: Imagemagick rasterizes a SVG image on conversion. As a result, the
#       image becomes not scalable. To avoid that, please use other image
#       converters like sphinxcontrib-svg2pdfconverter (which uses Inkscape
#       or rsvg-convert).
#
# https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter
#


# -- Options for sphinx.ext.inheritance_diagram -- Include inheritance diagrams
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/inheritance.html
#


# -- Options for sphinxcontrib-svg2pdfconverter -- Convert SVG images to PDF -
#
# https://pypi.org/project/sphinxcontrib-svg2pdfconverter/
#
#    sphinxcontrib.inkscapeconverter -- either Inkscape,
#    sphinxcontrib.rsvgconverter     -- rsvg-convert from libRSVG or
#    sphinxcontrib.cairosvgconverter -- CairoSVG
#

# Path to Inkscape binary. By default, this is:
#inkscape_converter_bin = 'inkscape'

# Additional command-line arguments for Inkscape, as a list.
# By default, this is:
#inkscape_converter_args = ['--export-area-drawing']

# Path to RSVG converter binary. By default, this is:
#rsvg_converter_bin = 'rsvg-convert'

# Additional command-line arguments for the RSVG converter, as a list.
# By default, this is the emtpy list:
#rsvg_converter_args = []


# -- Options for sphinxcontrib.email -- Email address obfuscator -------------
#
# https://github.com/sphinx-contrib/email/blob/v0.2.1/README.rst
#


# -- Options for sphinxcontrib.bibtex -- Insert BibTeX citations -------------
#
# https://sphinxcontrib-bibtex.readthedocs.io/en/stable/
#


# -- Options for sphinxcontrib.blockdiag -- Draw block diagrams --------------
# -- Options for sphinxcontrib.seqdiag -- Draw sequence diagrams -------------
# -- Options for sphinxcontrib.actdiag -- Draw activity diagrams -------------
# -- Options for sphinxcontrib.nwdiag -- Draw network diagrams ---------------
# -- Options for sphinxcontrib.rackdiag -- Draw rack diagrams ----------------
# -- Options for sphinxcontrib.packetdiag -- Draw packet diagrams ------------
#
# http://blockdiag.com/en/blockdiag/sphinxcontrib.html#configure-sphinx
# http://blockdiag.com/en/seqdiag/sphinxcontrib.html#configure-sphinx
# http://blockdiag.com/en/actdiag/sphinxcontrib.html#configure-sphinx
# http://blockdiag.com/en/nwdiag/sphinxcontrib.html#configure-sphinx
#

# Fontpath for blockdiag (truetype font), The default is None.
blockdiag_fontpath = '{}/DejaVuSansCondensed.ttf'.format(path_dejavu)
seqdiag_fontpath = blockdiag_fontpath
actdiag_fontpath = blockdiag_fontpath
nwdiag_fontpath = blockdiag_fontpath
rackdiag_fontpath = '{}/DejaVuSansMono.ttf'.format(path_dejavu)
packetdiag_fontpath = rackdiag_fontpath

# Fontmap for blockdiag (maps fontfamily name to truetype font).
# The default is None.
# blockdiag_fontmap = '{}/_extensions/blockdiag.fontmap'.format(DOCSRC)
# seqdiag_fontmap = '{}/_extensions/seqdiag.fontmap'.format(DOCSRC)
# actdiag_fontmap = '{}/_extensions/actdiag.fontmap'.format(DOCSRC)
# nwdiag_fontmap = '{}/_extensions/nwdiag.fontmap'.format(DOCSRC)
# rackdiag_fontmap = '{}/_extensions/nwdiag.fontmap'.format(DOCSRC)
# packetdiag_fontmap = '{}/_extensions/nwdiag.fontmap'.format(DOCSRC)

# If this is True, blockdiag generates images with anti-alias filter.
# The default is False.
blockdiag_antialias = True
seqdiag_antialias = blockdiag_antialias
actdiag_antialias = blockdiag_antialias
nwdiag_antialias = blockdiag_antialias
rackdiag_antialias = blockdiag_antialias
packetdiag_antialias = blockdiag_antialias

# If this is True, blockdiag generates images with transparency background.
# The default is False.
blockdiag_transparency = True
seqdiag_transparency = blockdiag_transparency
actdiag_transparency = blockdiag_transparency
nwdiag_transparency = blockdiag_transparency
rackdiag_transparency = blockdiag_transparency
packetdiag_transparency = blockdiag_transparency

# You can specify image format on converting docs to HTML; accepts 'PNG'
# or 'SVG'. The default is 'PNG'.
blockdiag_html_image_format = 'SVG'
seqdiag_html_image_format = blockdiag_html_image_format
actdiag_html_image_format = blockdiag_html_image_format
nwdiag_html_image_format = blockdiag_html_image_format
rackdiag_html_image_format = blockdiag_html_image_format
packetdiag_html_image_format = blockdiag_html_image_format

# You can specify image format on converting docs to TeX; accepts 'PNG'
# or 'PDF'. The default is 'PNG'.
blockdiag_latex_image_format = 'PDF'
seqdiag_latex_image_format = blockdiag_latex_image_format
actdiag_latex_image_format = blockdiag_latex_image_format
nwdiag_latex_image_format = blockdiag_latex_image_format
rackdiag_latex_image_format = blockdiag_latex_image_format
packetdiag_latex_image_format = blockdiag_latex_image_format

# Enable debug mode of blockdiag.
# The default is False.
# blockdiag_debug = True
# seqdiag_debug = True
# actdiag_debug = True
# nwdiag_debug = True
# rackdiag_debug = True
# packetdiag_debug = True


# -- Options for sphinxcontrib.programoutput -- Insert output of commands ----
#
# https://sphinxcontrib-programoutput.readthedocs.io/en/stable/
#


# -- Options for sphinxcontrib.spelling -- Spelling Checker ------------------
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/
#

# String specifying the language, as understood by PyEnchant and enchant.
# Defaults to en_US for US English.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#input-options
#
# spelling_lang = 'en_US'

# String specifying a file containing a list of words known to be spelled
# correctly but that do not appear in the language dictionary selected
# by spelling_lang. The file should contain one word per line. Refer to
# the PyEnchant tutorial for details.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#input-options
#
# spelling_word_list_filename = 'spelling_wordlist.txt'
spelling_word_list_filename = [
    '{}/spelling_wordlist.txt'.format(path_templates),
    '/usr/share/dict/american-english-huge',
    '/usr/share/dict/ngerman',
]

# A list of glob-style patterns that should be ignored when checking
# spelling. They are matched against the source file names relative
# to the source directory, using slashes as directory separators on
# all platforms. See Sphinx's exclude_patterns option for more details
# on glob-style patterns.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#input-options
#
spelling_exclude_patterns = [
    'doc*.rsti',
    'index*.rst',
]

# Boolean controlling whether suggestions for misspelled words are printed.
# Defaults to False.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#output-options
#
spelling_show_suggestions = True

# Boolean controlling whether the contents of the line containing each
# misspelled word is printed, for more context about the location of
# each word. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#output-options
#
# spelling_show_whole_line = True

# Boolean controlling whether words that look like package names from PyPI
# are treated as spelled properly. When True, the current list of package
# names is downloaded at the start of the build and used to extend the list
# of known words in the dictionary. Defaults to False.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_pypi_package_names = False

# Boolean controlling whether words that follow the CamelCase conventions
# used for page names in wikis should be treated as spelled properly.
# Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_wiki_words = True

# Boolean controlling treatment of words that appear in all capital letters,
# or all capital letters followed by a lower case s. When True, acronyms are
# assumed to be spelled properly. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_acronyms = True

# Boolean controlling whether names built in to Python should be treated as
# spelled properly. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_python_builtins = True

# Boolean controlling whether words that are names of modules found on
# sys.path are treated as spelled properly. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_importable_modules = True

# Boolean controlling treatment of contributor names extracted from the git
# history as spelled correctly, making it easier to refer to the names in
# acknowledgments. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_contributor_names = True

# List of filter classes to be added to the tokenizer that produces words
# to be checked. The classes should be derived from enchant.tokenize.Filter.
# Refer to the PyEnchant tutorial for examples.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_filters = []


# -- Options for sphinxcontrib.tikz -- Draw PGF/TikZ LaTeX pictures ----------
#
# https://sphinxcontrib-tikz.readthedocs.io/
# https://sphinxcontrib-tikz.readthedocs.io/en/latest/#configuration
# https://bitbucket.org/philexander/tikz/src/master/README.rst
#

# Choose the image processing 'suite', either 'pdf2svg', 'GhostScript',
# 'ImageMagick', or 'Netpbm' ('pdf2svg' by default):
# tikz_proc_suite = 'ImageMagick'
if not on_rtd: tikz_proc_suite = 'pdf2svg'

# Choose an image resolution (ignored if tikz_proc_suite is 'pdf2svg').
# The default is 184.
if on_rtd: tikz_resolution = 92

# Enable/disable transparent graphics. The default is True.
tikz_transparent = True

# Add some <string> to the sub process LaTeX preamble for the html build
# target. The default is None.
# tikz_latex_preamble = ''
f = open('{}/fontpkg.tex.in'.format(path_templates), 'r+')
tikz_latex_preamble = f.read().format (
    dejavu = path_dejavu + '/',
    wenquanyi = path_wenquanyi + '/',
)

# Add some \usetikzlibrary{<string>} to the sub process LaTeX preamble
# for the html build target. The default is None.
tikz_tikzlibraries = '''%%
    arrows,%%
    calendar,%%
    folding,%%
    matrix,%%
    shapes'''


# -- Options for sphinx_tabs.tabs -- Create tabbed content -------------------
#
# https://sphinx-tabs.readthedocs.io/en/stable/
#


# -- Options for sphinx_panels -- Create panels in a grid layout or drop-downs
#
# https://sphinx-panels.readthedocs.io/en/stable/
#
# !!! CONFLICTS WITH sphinx_tabs.tabs !!!
#

# Change the delimiter regexes used to detect panels, header, footer.
# Default is: panels_delimiters = (r"^\-{3,}$", r"^\^{3,}$", r"^\+{3,}$")


# -- Options for linuxdoc.rstFlatTable -- Create flat table content ----------
#
# https://return42.github.io/linuxdoc/
# https://github.com/return42/linuxdoc
#


# -- Options for matplotlib.sphinxext.plot_directive -- Including Matplotlib -
#
# https://matplotlib.org/api/sphinxext_plot_directive_api.html#configuration-options
#

# Base directory, to which plot directive file names are relative to.
# If None or empty, file names are relative to the directory where the
# file containing the directive is.
plot_basedir = '{}/mplplots'.format(path_images)

# By default, the working directory will be changed to the directory of
# the example, so the code can get at its data files, if any. Also its
# path will be added to sys.path so it can import any helper modules
# sitting beside it. This configuration option can be used to specify
# a central directory (also added to sys.path) where data files and
# helper modules for all code are located.
plot_working_directory = '{}/mplplots'.format(path_images)

# Code that should be executed before each plot. If not specified or
# None it will default to a string containing:
# 'import numpy as np; from matplotlib import pyplot as plt'
f = open('{}/matplotlib_pre.py'.format(path_templates), 'r+')
plot_pre_code = f.read()

# Default value for the include-source option.
plot_include_source = True

# Whether to show a link to the source in HTML.
plot_html_show_source_link = False

# Whether to show links to the files in HTML.
plot_html_show_formats = True


# -- Options for ldsp.* -- LOCAL EXTENSIONS ----------------------------------
#

# Using variables inside reST w/o 'rst_prolog' or 'rst_epilog'.
ultimate_replacements = {
    '{plot_basedir}': os.path.relpath(plot_basedir, DOCSRC),
    '{plot_workdir}': os.path.relpath(plot_working_directory, DOCSRC),
    '{plot_preincl}': '/' + os.path.relpath(
                      '{}/matplotlib_pre.py'.format(path_templates), DOCSRC),
}


# -- Options for LaTeX output ------------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/latex.html
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-latex-output
#
# https://www.sphinx-doc.org/en/master/latex.html
# https://blog.michael.franzl.name/2014/12/10/xelatex-unicode-font-fallback-unsupported-characters/
# https://tex.stackexchange.com/questions/344100/
# https://tex.stackexchange.com/questions/323575/

# TODO: evaluate possible admonitionbox override, see:
#       http://stackoverflow.com/a/13661732
# Left aligne captions: http://tex.stackexchange.com/questions/136688/how-to-align-caption-with-table

f = open('{}/extrapackages.tex'.format(path_templates), 'r+')
latex_custom_extrapackages = f.read()

f = open('{}/passoptstopackages.tex.in'.format(path_templates), 'r+')
latex_custom_passoptionstopackages = f.read().format (
    producer = 'Sphinx ' + build_sphinx,
    creator = 'Sphinx ' + build_sphinx,
    publisher = publisher,
    subject = about,
    keywords = keywords,
)

f = open('{}/preamble.tex.in'.format(path_templates), 'r+')
latex_custom_preamble = f.read().format (
    publisher = publisher,
    contactaddr = contactaddr,
    contactemail = contactemail,
)

f = open('{}/fontpkg.tex.in'.format(path_templates), 'r+')
latex_custom_fontpkg = f.read().format (
    dejavu = path_dejavu + '/',
    wenquanyi = path_wenquanyi + '/',
)

f = open('{}/utf8extra.tex'.format(path_templates), 'r+')
latex_custom_utf8extra = f.read()

# The LaTeX engine to build the docs. The setting can have the
# following values:
#   'pdflatex' – PDFLaTeX (default, limited Unicode characters support)
#   'xelatex' – XeLaTeX
#   'lualatex' – LuaLaTeX
#   'platex' – pLaTeX (default if language is 'ja')
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_engine
#
latex_engine = 'xelatex'

# A dictionary that contains LaTeX snippets overriding those Sphinx
# usually puts into the generated .tex files.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_elements
# http://www.sphinx-doc.org/en/3.x/latex.html#latex-elements-confval
# http://www.sphinx-doc.org/en/3.x/latex.html
#
latex_elements = {
    #
    # Keys that you may want to override include:
    #
    'extraclassoptions': 'table',

    # Paper size option of the document class ('letterpaper' or 'a4paper'),
    # default 'letterpaper'.
    'papersize': 'a4paper',

    # Point size option of the document class ('10pt', '11pt' or '12pt'),
    # default '10pt'.
    'pointsize': '10pt',

    # "babel" package inclusion, default r'\usepackage{babel}'.
    'babel': r'\usepackage[english]{babel}',

    # "geometry" package inclusion, default r'\usepackage{geometry}'.
    'geometry': r'\usepackage[bottom=4cm, left=2.4cm, right=2.4cm]{geometry}',

    # Font package inclusion, default r'\usepackage{times}' (which uses Times
    # and Helvetica). You can set this to '' to use the Computer Modern fonts.
    # Defaults to '' when the language uses the Cyrillic script.
    # For xelatex it defaults to: '''\setmainfont{FreeSerif}[..]
    # \setsansfont{FreeSans}[..]\setmonofont{FreeMono}[..]'''
    'fontpkg': latex_custom_fontpkg,

    # Inclusion of the "fncychap" package (which makes fancy chapter titles),
    # default r'\usepackage[Bjarne]{fncychap}' for English documentation,
    # r'\usepackage[Sonny]{fncychap}' for internationalized docs (because the
    # "Bjarne" style uses numbers spelled out in English). Other "fncychap"
    # styles you can try include "Lenny", "Glenn", "Conny" and "Rejne". You can
    # also set this to '' to disable fncychap.
#   'fncychap': r'\usepackage[Sonny]{fncychap}',
#   'fncychap': r'\usepackage[Bjarne]{fncychap}',
    'fncychap': r'\usepackage[Bjornstrup]{fncychap}',

    # Additional package inclusion, default empty.
    'extrapackages': latex_custom_extrapackages,

    # "PassOptionsToPackage" call, default empty.
    'passoptionstopackages': latex_custom_passoptionstopackages,

    # Additional preamble content, default empty.
    'preamble': latex_custom_preamble,

    # Latex figure (float) alignment, default 'htbp' (here, top, bottom, page).
    # Whenever an image doesn't fit into the current page, it will be 'floated'
    # into the next page but may be preceded by any other text. If you don't
    # like this behavior, use 'H' which will disable floating and position
    # figures strictly in the order they appear in the source.
    'figure_align': 'H',

    # Latex number figure format, default empty.
#   'numfig_format': '',

    #
    # Keys that don’t need be overridden unless in special cases are:
    #

    # "inputenc" package inclusion, defaults to r'\usepackage[utf8]{inputenc}'
    # when using pdflatex. Otherwise unset.
#   'inputenc': r'\usepackage[utf8]{inputenc}',

    # Unicode character declaration, for xelatex defaults to:
    # \catcode`^^^^00a0\active\protected\def^^^^00a0{\leavevmode\nobreak\ }
    'utf8extra': latex_custom_utf8extra,

    # "cmap" package inclusion, default r'\usepackage{cmap}'.
#   'cmappkg': r'\usepackage{cmap}',

    # "fontenc" package inclusion, default r'\usepackage[T1]{fontenc}' and
    # r'\usepackage{fontspec}\defaultfontfeatures[\rmfamily,\sffamily,\ttfamily]{}'
    # in case of xelatex for non-mandarin languages.
#   'fontenc': r'\usepackage[T1]{fontenc}',

    # "amsmath" package inclusion, default r'\usepackage{amsmath,amssymb,amstext}'.
#   'amsmath': r'\usepackage{amsmath,amssymb,amstext}',

    # Value that prefixes 'release' element on title page, default 'Release'.
    'releasename': 'Version',

    # "makeindex" call, default r'\makeindex'. Override if you want to
    # generate a differently-styled index page.
#   'makeindex': r'\makeindex',

    # "maketitle" call, default r'\sphinxmaketitle'. Override if you want to
    # generate a differently-styled title page.
#   'maketitle': r'\sphinxmaketitle',

    # "tableofcontents" call, default r'\sphinxtableofcontents'. Override if
    # you want to generate a different table of contents or put content between
    # the title page and the TOC.
#   'tableofcontents': r'\sphinxtableofcontents',

    # "printindex" call, the last thing in the file, default r'\printindex'.
    # Override if you want to generate the index differently or append some
    # content after the index.
    'printindex': r'\footnotesize\raggedright\printindex',

    # Commands used to display transitions, default r'\n\n\bigskip\hrule{}\bigskip\n\n'.
    # Override if you want to display transitions differently.
#   'transition': r'\n\n\bigskip\hrule{}\bigskip\n\n',

    #
    # Keys that are set by other options and therefore should not be
    # overridden are: 'docclass' 'classoptions' 'extraclassoptions'
    #                 'contentsname' 'title' 'date' 'release'
    #                 'author' 'logo' 'makeindex' 'shorthandoff'
    #                 'tocdepth' 'pageautorefname'
    #

    # Get rid of evenly numbered empty pages (default book style)
#   'classoptions': ',openany,oneside',
    'classoptions': ',openany',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_documents
#
latex_documents = [
    (master_doc, basename + '.tex', title, author, 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_logo
#
#latex_logo = None
latex_logo = '{}/lpn.pdf'.format(path_images)

# If true, show page references after internal links. Default: False.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_show_pagerefs
#
latex_show_pagerefs = True

# If true, show URL addresses after external links. Default: 'no'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_show_urls
#
# latex_show_urls = 'no'
# latex_show_urls = 'footnote'
# latex_show_urls = 'inline'

# A list of file names, relative to the configuration directory, to copy
# to the build directory when building LaTeX output. This overrides the
# files which is provided from Sphinx such as sphinx.sty.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_additional_files
#
# latex_additional_files = [ '{}/_extra/file.ext'.format(DOCSRC), ]

# Documents to append as an appendix to all manuals.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_appendices
#
#latex_appendices = [
#    'appendix',
#    'glossary',
#    'bibliography',
#]

# If false, no module index is generated.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_domain_indices
#
#latex_domain_indices = True


# -- Options for HTML output -------------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-html-output
#

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_theme
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_theme_path
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_theme_options
#
html_theme = 'sphinx_rtd_theme'

#
# https://sphinx-rtd-theme.readthedocs.io/en/0.5.0/configuring.html
#
html_theme_options = {
    'canonical_url': 'https://lpn-doc-sphinx-primer-devel.readthedocs.io/',
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': True,
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_title
#
html_title = title

# This value determines the text for the permalink; it defaults to "¶".
# Set it to None or the empty string to disable permalinks.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_add_permalinks
#
#html_add_permalinks = ""

# A shorter title for the navigation bar.  Default is the same as html_title.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_short_title
#
#html_short_title = None

# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_logo
#
html_logo = '{}/lpn.svg'.format(path_images)

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_favicon
#
html_favicon = '{}/lpn.ico'.format(path_images)

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_static_path
#
html_static_path = ['{}'.format(path_static)]

# A list of CSS files. The entry must be a filename string or a tuple
# containing the filename string and the attributes dictionary. The
# filename must be relative to the html_static_path, or a full URI
# with scheme. The attributes is used for attributes of <link> tag.
# It defaults to an empty list.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_css_files
#
html_css_files = [
    'fonts/DejaVu.css',
    'fonts/WenQuanYi.css',
    'css/force-dejavu.css',
    'css/fix-cite.css',
    'css/fix-float.css',
    'css/strikethrough.css',
    'css/tweaks-sphinx_rtd_theme.css',
]

# A list of JavaScript filename. The entry must be a filename string or
# a tuple containing the filename string and the attributes dictionary.
# The filename must be relative to the html_static_path, or a full URI
# with scheme. The attributes is used for attributes of <script> tag.
# It defaults to an empty list.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_js_files
#
#html_js_files = []

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_extra_path
#
html_extra_path = ['{}'.format(path_extra)]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_last_updated_fmt
#
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_use_smartypants
#
#html_use_smartypants =

# Custom sidebar templates, maps document names to template names.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_sidebars
#
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_additional_pages
#
#html_additional_pages = {}

# If false, no module index is generated.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_domain_indices
#
html_domain_indices = False

# If false, no index is generated.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_use_index
#
html_use_index = True

# If true, the index is split into individual pages for each letter.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_split_index
#
html_split_index = True

# If true, links to the reST sources are added to the pages.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_show_sourcelink
#
html_show_sourcelink = True

# Suffix to be appended to source links.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_sourcelink_suffix
#
html_sourcelink_suffix = '.txt'

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_show_sphinx
#
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_show_copyright
#
# html_show_copyright = tags.has('development')
html_show_copyright = True

# If true, license is shown in the HTML footer. Default is True.
html_show_license = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_use_opensearch
#
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_file_suffix
#
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_search_language
#
#html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_search_options
#
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_search_scorer
#
html_search_scorer = '{}/js/scorer.js'.format(path_static)


# -- Options for Epub output ----------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-epub-output
#

# Bibliographic Dublin Core info.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_title
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_author
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_publisher
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_copyright
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_description
#
epub_title = title
epub_author = author
epub_publisher = publisher
epub_copyright = copyright
epub_description = about

# The basename for the epub file. It defaults to the project name.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_basename
#
epub_basename = basename

# The HTML theme for the epub output. Since the default themes are not optimized
# for small screen space, using the same theme for HTML and epub output is
# usually not wise. This defaults to 'epub', a theme designed to save visual
# space.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_theme
#
#epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or en if the language is not set.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_language
#
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_scheme
#
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_identifier
#
#epub_identifier = ''

# A unique identification for the text.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_uid
#
#epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_cover
#
#epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_guide
#
#epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_pre_files
#
#epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_post_files
#
#epub_post_files = []

# A list of files that should not be packed into the epub file.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_exclude_files
#
epub_exclude_files = [
    '.nojekyll',
    'search.html',
]

# The depth of the table of contents in toc.ncx.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_tocdepth
#
#epub_tocdepth = 3

# Allow duplicate toc entries.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_tocdup
#
#epub_tocdup = True

# Choose between 'default' and 'includehidden'.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_tocscope
#
#epub_tocscope = 'default'

# Fix unsupported image types using the PIL.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_fix_images
#
#epub_fix_images = False

# Scale large images.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_max_image_width
#
#epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_show_urls
#
#epub_show_urls = 'inline'

# If false, no index is generated.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-epub_use_index
#
#epub_use_index = True


# -- Options for HTML help output --------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-html-help-output
#

# Output file base name for HTML help builder.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-htmlhelp_basename
#
htmlhelp_basename = basename


# -- Options for QtHelp output -----------------------------------------------
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-qthelp-output
#

# Output file base name for QtHelp builder.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-qthelp_basename
#
qthelp_basename = basename

# The namespace for the qthelp file. It defaults to
# org.sphinx.<project_name>.<project_version>.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-qthelp_namespace
#
qthelp_namespace = namespace


# -- Options for Text output ----------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-text-output
#

# Determines which end-of-line character(s) are used in text
# output: 'unix', 'windows', or 'native'. Default: 'unix'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-text_newlines
#
# text_newlines = 'unix'

# A string of 7 characters that should be used for underlining
# sections. The first character is used for first-level headings,
# the second for second-level headings and so on. The default is '*=-~"+`'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-text_sectionchars
#
text_sectionchars = '*=-~"+`'


# -- Options for Texinfo output -------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-texinfo-output
#

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-texinfo_documents
#
texinfo_documents = [
    (master_doc, basename, title, author, publisher, about, category),
]

# Documents to append as an appendix to all manuals.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-texinfo_appendices
#
#texinfo_appendices = []

# If false, no module index is generated.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-texinfo_domain_indices
#
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-texinfo_show_urls
#
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-texinfo_no_detailmenu
#
#texinfo_no_detailmenu = False


# -- Options for manual page output ---------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-manual-page-output
#

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-man_pages
#
man_pages = [
  (master_doc, basename, title, author, 1),
]

# If true, show URL addresses after external links.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-man_show_urls
#
#man_show_urls = False
