# -*- coding: utf-8 -*-
#
# Li-Pro.Net Sphinx Primer documentation build configuration file,
# created by sphinx-quickstart on Sat Sep  5 12:37:04 2020.
#
# The configuration directory must contain a file named conf.py.
# This file (containing Python code) is execfile()d with the
# current directory set to its containing dir and is called the
# "build configuration file" and contains (almost) all configuration
# needed to customize Sphinx input and output behavior.
#
# This file only contains a selection of the most common options.
# For a full list see the documentation:
#
# http://www.sphinx-doc.org/en/3.x/config
#
# An optional file docutils.conf can be added to the configuration
# directory to adjust Docutils configuration if not otherwise overridden
# or set by Sphinx.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.


# -- Path setup --------------------------------------------------------------

import sphinx
import sys
import os

if "DOCSRC" not in os.environ:
    DOCSRC = os.path.abspath(os.getcwd())
else:
    DOCSRC = os.path.abspath(os.environ["DOCSRC"])

# Add the 'extensions' directory to sys.path, to enable finding Sphinx
# extensions within. If extensions (or modules to document with autodoc)
# are in another directory, add these directories to sys.path here. If the
# directory is relative to the documentation root, use os.path.abspath to
# make it absolute, like shown here.
sys.path.insert(0, os.path.join(DOCSRC, '_extensions'))


# -- Project information -----------------------------------------------------

project = 'Li-Pro.Net Sphinx Primer'
author = 'The LP/N Documentation Team'
publisher = 'Li–Pro.Net'
copyright = '2020, ' + publisher + ', ' + author + ' and individual contributors'
keywords = 'sphinx,howto,primer'

# The short X.Y version
version = '0.0'

# The full version, including alpha/beta/rc tags
release = '0.0.1'


# -- Specific configuration --------------------------------------------------

if tags.has('release'):  # pylint: disable=undefined-variable
    is_release = True
    docs_title = 'Docs / %s' %(version)
else:
    is_release = False
    docs_title = 'Docs / Latest'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-needs_sphinx
#
needs_sphinx = '3.2.1'
build_sphinx = sphinx.__version__

# This value can be a dictionary specifying version requirements for
# extensions in 'extensions'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-needs_extensions
#
needs_extensions = {
#   'sphinx.ext.autodoc':                       needs_sphinx,
#   'sphinx.ext.autosummary':                   needs_sphinx,
#   'sphinx.ext.autosgen':                      needs_sphinx,
    'sphinx.ext.autosectionlabel':              needs_sphinx,
    'sphinx.ext.doctest':                       needs_sphinx,
    'sphinx.ext.coverage':                      needs_sphinx,
    'sphinx.ext.todo':                          needs_sphinx,
    'sphinx.ext.ifconfig':                      needs_sphinx,
    'sphinx.ext.intersphinx':                   needs_sphinx,
    'sphinx.ext.extlinks':                      needs_sphinx,
#   'sphinx.ext.viewcode':                      needs_sphinx,
#   'sphinx.ext.linkcode':                      needs_sphinx,
#   'sphinx.ext.imgmath':                       needs_sphinx,
    'sphinx.ext.mathjax':                       needs_sphinx,
#   'sphinx.ext.jsmath':                        needs_sphinx,
#   'sphinx.ext.graphviz':                      needs_sphinx,
#   'sphinx.ext.inheritance_diagram':           needs_sphinx,
}

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-extensions
#
extensions = [
#   'sphinx.ext.autodoc',
#   'sphinx.ext.autosummary',
#   'sphinx.ext.autosgen',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.doctest',
    'sphinx.ext.coverage',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx.ext.intersphinx',
    'sphinx.ext.extlinks',
#   'sphinx.ext.viewcode',
#   'sphinx.ext.linkcode',
#   'sphinx.ext.imgmath',
    'sphinx.ext.mathjax',
#   'sphinx.ext.jsmath',
#   'sphinx.ext.graphviz',
#   'sphinx.ext.inheritance_diagram',
]


# -- Sphinx Basic Configuration ----------------------------------------------

# Add any paths that contain templates here, relative to this directory.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-templates_path
#
templates_path = ['{}/_templates'.format(DOCSRC)]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-internationalization
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-language
#
language = 'en'

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-source_suffix
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-source_encoding
#
#source_encoding = 'utf-8-sig'

# If given, a dictionary of parser classes for different source suffices.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-source_parsers
#
#source_parsers = {'.md': 'recommonmark.parser.CommonMarkParser'}

# The master toctree document.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-master_doc
#
master_doc = 'index'

# There are two options for replacing |today|.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-today
#
# Either, you set today to some non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-exclude_patterns
#
exclude_patterns = []

# This change will allow us to use bare back-tick notation to let
# Sphinx hunt for a reference, starting with normal "document"
# references such as :ref:, but also including :c: and :cpp: domains
# (potentially) helping with API (doxygen) references simply by using
# `name`
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-primary_domain
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-default_role
#
#primary_domain = 'cpp'
default_role = 'any'

# If true, '()' will be appended to :func: etc. cross-reference text.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-add_function_parentheses
#
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-add_module_names
#
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-show_authors
#
#show_authors = False
show_authors = True

# The name of the Pygments (syntax highlighting) style to use.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-pygments_style
#
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-modindex_common_prefix
#
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-keep_warnings
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-suppress_warnings
#
#keep_warnings = False
#suppress_warnings = []

# If true, figures, tables and code-blocks are automatically numbered if they
# have a caption. At same time, the numref role is enabled. For now, it works
# only with the HTML builder and LaTeX builder. Default is False.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig
#
numfig = True

# A dictionary mapping 'figure', 'table' and 'code-block' to strings that are
# used for format of figure numbers. Default is to use 'Fig. %s' for 'figure',
# 'Table %s' for 'table' and 'Listing %s' for 'code-block'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig_format
#
numfig_format = {
    'code-block': 'Listing %s',
    'sections': 'Section %s',
    'figure': 'Figure %s',
    'table': 'Table %s',
}

# The scope of figure numbers, that is, the numfig feature numbers figures in
# which scope. 0 means “whole document”. 1 means “in a section”. Sphinx numbers
# like x.1, x.2, x.3... 2 means “in a subsection”. Sphinx numbers like x.x.1,
# x.x.2, x.x.3..., and so on. Default is 1.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig_secnum_depth
#
numfig_secnum_depth = 1

# Set this option to True if you want all displayed math to be numbered.
# The default is False.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-math_number_all
#
math_number_all = True

# A string used for formatting the labels of references to equations. The
# {number} place-holder stands for the equation number. Example: 'Eq.{number}'
# gets rendered as, for example, Eq.10.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-math_eqref_format
#
math_eqref_format = 'Equastion {number}'

# If True, displayed math equations are numbered across pages when numfig is
# enabled. The numfig_secnum_depth setting is respected. The eq, not numref,
# role must be used to reference equation numbers. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-math_numfig
#
# math_numfig = False

# A URL to cross-reference manpage directives.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-manpages_url
#
manpages_url = 'https://manpages.debian.org/{path}'

# A User-Agent of Sphinx. It is used for a header on HTTP access
# (ex. linkcheck, intersphinx and so on).
# Default is "Sphinx/X.Y.Z requests/X.Y.Z python/X.Y.Z".
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-user_agent
#
#user_agent = 'Sphinx/X.Y.Z requests/X.Y.Z python/X.Y.Z

# If true, Sphinx verifies server certifications. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-tls_verify
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-tls_cacerts
#
#tls_verify = False

# some configuration for linkcheck builder
#   noticed that we're getting false-positive link errors on different server,
#   I suspect because it's taking too long for the server to respond so bump
#   up the timeout (default=5) and turn off anchor checks (so only a HEAD
#   request is done - much faster). Leave the ignore commented in case we want
#   to remove different server link checks later...

#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_ignore
#
#linkcheck_ignore = [r'http://localhost:\d+/']
linkcheck_ignore = [
    r'http://localhost:\d+/',
]

#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_timeout
#
linkcheck_timeout = 60

# The number of worker threads to use when checking links.
# Default is 5 threads.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_workers
#
# linkcheck_workers = 5
linkcheck_workers = 10

# True or false, whether to check the validity of #anchors in links.
# Since this requires downloading the whole document, it’s considerably
# slower when enabled. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_anchors
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_anchors_ignore
#
#linkcheck_anchors = True
linkcheck_anchors = False


# -- Options for HTML output -------------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-html-output
#

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['{}/_static'.format(DOCSRC)]

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_extra_path
#
html_extra_path = ['{}/_extra'.format(DOCSRC)]


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/3/': None}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
